# Generated by Django 3.1.3 on 2020-11-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
